### ISSUE TITLE
When navigating directly to `/Documents` you get an access denied error

### ISSUE THREAD

**Issue by shafkevi** [aws-samples/Serverless-Retrieval-Augmented-Generation-RAG-on-AWS#24]
You can navigate using the React router by clicking around the screen, but if you navigate directly to the `/Documents` path you get an Access Denied error. This likely just requires a redirection rule in the Cloudfront/S3 connection.

**Comment by giusedroid** [comment]
ah yeah, we use react router, we need to config default redirects on CloudFront. What a noob!

**Comment by giusedroid** [comment]
addressing in #19

**Comment by giusedroid** [comment]
closed with #19
